### ISSUE TITLE
zupt status always set to true

### ISSUE THREAD

**Issue by giafranchini** [Fixit-Davide/imu_zupt#1]
In the bag `2023-07-03_17-07-44____20_minutes_test_1` the topic `/localisation/imu/zupt_status` has data always set to true. 
This leads to a constant orientation and zero angular velocity in topic `/localisation/imu/data_zupt`.

**Comment by Fixit-Davide** [comment]
Try to see if the imu_zupt node subscribes correctly to the rover_status's topic while playing the rosbag.
Check also that the imu_zupt node's config file contains the correct name of the topic.  
https://github.com/roncapat/RoXY-AutoNav-Rover-Launchers/blob/humble/master/launch/localisation_zed_record.launch.py

**Comment by giafranchini** [comment]
The rosbag that I mentioned publishes already the topic `/localisation/imu/zupt_status`, so I have no control on config parameters. I'll do some tests with new data in the next days.

**Comment by Fixit-Davide** [comment]
I think that I found the bug.
robot_status sets the flag to True if the rover is not moving. Imu_zupt enters the imu_callback only if the condition is set to False.
Just remove the **not** in the if() condition.

**Comment by roncapat** [comment]
Might be better to have a PR with a test case & the proposed fix.
