### ISSUE TITLE
README mismatch over current functionality 

### ISSUE THREAD

**Issue by roncapat** [Fixit-Davide/imu_zupt#6]
The README currently describes the subscription to an odometry message, while boolean rover status is now expected by code.

**Comment by Fixit-Davide** [comment]
Closed 4ed86e9e0a32512aaa18ac9b67e507aad8d778ba

**Comment by roncapat** [comment]
I would also add a disclaimer stating that input IMU topic must contain orientation data and that this node is not an orientation estimator.
